[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sparkrobot-common"
version = "0.1.0"
description = "SparkRobot 通用库 - 配置、日志、工具函数"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "uuid6>=2025.0.1; python_version < \"3.14\"",
    "watchdog>=6.0.0; python_version < \"3.14\""
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
sparkrobot_common = ["py.typed"]

[tool.setuptools]
include-package-data = true

# ============================
# 下面是 lint/typecheck 配置
# ============================

[tool.ruff]
line-length = 200
exclude = ["build", ".venv", ".git", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "C", "B", "Q"]

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.black]
line-length = 120
target-version = ["py310"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["src"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
explicit_package_bases = false # 包根是 ./而不是 ./src
check_untyped_defs = true 
files = ["src"]
