<?xml version="1.0"?>
<package format="3">
  <name>sparkrobot_nav_bridge</name>
  <version>0.1.0</version>
  <description>机器狗运行时与 ROS2 导航栈的桥接节点</description>
  <maintainer email="elric@example.com">elric</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>action_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>rclpy</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
